apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot
spec:
  rules:
    - host: springboot.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: springboot-app
                port:
                  number: 80
