apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot
  namespace: springboot-app
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: springboot.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: springboot-app-springboot-app
                port:
                  number: 80
