{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-monitor
  namespace: monitoring
  labels:
    release: monitoring  # IMPORTANT â†’ must match your Prometheus instance
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  endpoints:
    - port: http
      path: {{ .Values.metrics.path }}
      interval: 15s
{{- end }}
